mod action;
mod activity;
mod activity_alias;
mod application;
mod category;
mod compatible_screens;
mod data;
mod grant_uri_permission;
mod instrumentation;
mod intent_filter;
mod layout;
mod list_serde;
mod manifest;
mod meta_data;
mod path_permission;
mod permission;
mod permission_group;
mod permission_tree;
mod provider;
mod receiver;
mod resources;
mod service;
mod supports_gl_texture;
mod supports_screens;
mod ui_options;
mod uses_configuration;
mod uses_feature;
mod uses_library;
mod uses_permission;
mod uses_permission_sdk_23;
mod uses_sdk;

pub use action::*;
pub use activity::*;
pub use activity_alias::*;
pub use application::*;
pub use category::*;
pub use compatible_screens::*;
pub use data::*;
pub use grant_uri_permission::*;
pub use instrumentation::*;
pub use intent_filter::*;
pub use layout::*;
pub use manifest::*;
pub use meta_data::*;
pub use path_permission::*;
pub use permission::*;
pub use permission_group::*;
pub use permission_tree::*;
pub use provider::*;
pub use receiver::*;
pub use resources::*;
pub use service::*;
pub use supports_gl_texture::*;
pub use supports_screens::*;
pub use ui_options::*;
pub use uses_configuration::*;
pub use uses_feature::*;
pub use uses_library::*;
pub use uses_permission::*;
pub use uses_permission_sdk_23::*;
pub use uses_sdk::*;
